sudo: required
dist: trusty
addons:
  sonarcloud:
    organization: garethahealy-github
    token:
      secure: Mc1KuBodrPrIYVqYeOp0WAlDOvVV02fq1CmbWyjqxMMD5a4l/5YhM6HfXBZ9sA9JpWBilh3ockKgUib3iyChFNFNKAKsQ7RHPNznckHoObzTAwj1ThBTlD0hD5xvvTPkLa5gCsHHZpGU3R55dWJlldGFuFfK+b/2V8PUBS1j9DQ=
language: java
jdk:
- oraclejdk8
install:
- mvn -N io.takari:maven:wrapper -Dmaven=3.5.0
- java -version && javac -version && ./mvnw -version -B
before_script:
- ./mvnw dependency:go-offline -B
script:
- ./mvnw clean install -Dgpg.skip=true
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -B
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
